-- Ministry controlled vocabulary, lifted from the AdvSearch dropdown.
INSERT OR REPLACE INTO ministries (ministry_id, canonical_name) VALUES
  (0, 'All Ministries'),
  (80, 'AYUSH'),
  (61, 'Cabinet'),
  (62, 'Cabinet Committee Decisions'),
  (63, 'Cabinet Committee on Economic Affairs (CCEA)'),
  (70, 'Cabinet Committee on Infrastructure'),
  (75, 'Cabinet Committee on Investment'),
  (71, 'Cabinet Committee on Price'),
  (68, 'Cabinet Secretariat'),
  (56, 'Department of Atomic Energy'),
  (45, 'Department of Ocean Development'),
  (14, 'Department of Space'),
  (35, 'Election Commission'),
  (1330, 'Finance Commission'),
  (57, 'Min for Develop. of North-East Region'),
  (27, 'Min of Agriculture'),
  (58, 'Min of Agro & Rural Industries'),
  (41, 'Min of Chemicals and Fertilizers'),
  (26, 'Min of Civil Aviation'),
  (42, 'Min of Coal'),
  (16, 'Min of Commerce & Industry'),
  (24, 'Min of Comm. & Information Technology'),
  (60, 'Min of Company Affairs'),
  (39, 'Min of Consumer Affairs, Food & Public Distribution'),
  (66, 'Min of Corporate Affairs'),
  (17, 'Min of Culture'),
  (33, 'Min of Defence'),
  (48, 'Min of Disinvestment'),
  (73, 'Min of Drinking Water & Sanitation'),
  (67, 'Min of Earth Science'),
  (81, 'Min of Electronics & IT'),
  (30, 'Min of Environment and Forests'),
  (4, 'Min of External Affairs'),
  (15, 'Ministry of Finance'),
  (1340, 'Ministry of Fisheries, Animal Husbandry & Dairying'),
  (40, 'Min of Food Processing Industries'),
  (31, 'Min of Health and Family Welfare'),
  (53, 'Min of Heavy Ind. & Public Enterprises'),
  (5, 'Min of Home Affairs'),
  (32, 'Min of Housing & Urban Affairs'),
  (47, 'Min of Housing and Urban Poverty Alleviation'),
  (8, 'Min of Human Resource Development'),
  (11, 'Min of Information & Broadcasting'),
  (1336, 'Ministry of Jal Shakti'),
  (21, 'Min of Labour & Employment'),
  (7, 'Min of Law & Justice'),
  (51, 'Min of Micro,Small & Medium Enterprises'),
  (44, 'Min of Mines'),
  (65, 'Min of Minority Affairs'),
  (28, 'Min of New and Renewable Energy'),
  (59, 'Min of Overseas Indian Affairs'),
  (10, 'Min of Panchayati Raj'),
  (12, 'Min of Parliamentary Affairs'),
  (6, 'Min of Personnel, Public Grievances & Pensions'),
  (20, 'Min of Petroleum & Natural Gas'),
  (79, 'Min of Planning'),
  (52, 'Min of Power'),
  (23, 'Ministry of Railways'),
  (69, 'Min of Road Transport & Highways'),
  (43, 'Min of Rural Development'),
  (13, 'Min of Science & Technology'),
  (46, 'Min of Shipping'),
  (77, 'Min of Skill Development and Entrepreneurship'),
  (50, 'Min of Social Justice & Empowerment'),
  (55, 'Min of Statistics & Programme Implementation'),
  (18, 'Min of Steel'),
  (25, 'Min of Surface Transport'),
  (19, 'Min of Textiles'),
  (36, 'Ministry of Tourism'),
  (49, 'Min of Tribal Affairs'),
  (38, 'Ministry of Water Resources'),
  (64, 'Min of Women and Child Development'),
  (9, 'Min of Youth Affairs and Sports'),
  (78, 'NITI Aayog'),
  (1406, 'Office of Principal Scientific Advisor to GoI'),
  (72, 'Other Cabinet Committees'),
  (99, 'Others'),
  (1005, 'PIB Headquarters'),
  (22, 'Planning Commission'),
  (74, 'PMEAC'),
  (1, 'President''s Secretariat'),
  (3, 'Prime Minister''s Office'),
  (37, 'Special Service and Features'),
  (34, 'UPSC'),
  (2, 'Vice President''s Secretariat');
